/**
 * Auto-article topic pools for adanaailehukuku.com
 * Evergreen Turkish family-law intents — not city+keyword spam.
 */

export const TOPIC_POOL = [
  // Aile hukuku genel
  { topic: 'Aile hukuku nedir?', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Aile hukukunda en sık açılan davalar', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Aile mahkemesi hangi davalara bakar?', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Aile mahkemesinde dava süreci nasıl işler?', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Aile hukukunda arabuluculuk mümkün mü?', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Çocuğun üstün yararı ilkesi nedir?', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Evlilik sözleşmesi ne işe yarar?', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Mal rejimi sözleşmesi nasıl yapılır?', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Nişanın bozulması halinde haklar nelerdir?', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Nişan hediyeleri iade edilir mi?', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Evlenmenin iptali davası nedir?', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Evlat edinme süreci nasıl işler?', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },

  // Boşanma genel / süreç
  { topic: 'Boşanma davası nasıl açılır?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma davası ne kadar sürer?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma davasında görevli ve yetkili mahkeme', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma dilekçesinde neler yazılmalıdır?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma kararının kesinleşmesi ne demektir?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma kararından sonra nüfus kaydı nasıl düzeltilir?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma sonrası yeniden evlenme şartları', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma sonrası soyadı kullanımı', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Kadının boşanma sonrası soyadı seçimi', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma davasında istinaf süreci', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma davasında Yargıtay incelemesi', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanmada feragat ve kabul ne anlama gelir?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma davasında harç ve gider avansı', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanmada ayrı yaşama kararı nedir?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },

  // Anlaşmalı / çekişmeli
  { topic: 'Anlaşmalı boşanma şartları nelerdir?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Anlaşmalı boşanma protokolü nasıl hazırlanır?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Anlaşmalı boşanmada protokol değişikliği mümkün mü?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Anlaşmalı boşanma tek celsede biter mi?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Çekişmeli boşanma davası nasıl ilerler?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Çekişmeli boşanmada delil stratejisi', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Anlaşmalı boşanma çekişmeliye dönüşür mü?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Çekişmeli boşanmada sulh ve uzlaşma', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },

  // Boşanma sebepleri
  { topic: 'Evlilik birliğinin temelinden sarsılması', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Zina nedeniyle boşanma davası', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Aldatma nedeniyle boşanma ispatı', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Terk nedeniyle boşanma şartları', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Hayata kast nedeniyle boşanma', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Pek kötü veya onur kırıcı davranış nedeniyle boşanma', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Suç işleme ve haysiyetsiz hayat nedeniyle boşanma', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Akıl hastalığı nedeniyle boşanma', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Şiddet nedeniyle boşanma davası', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Ekonomik şiddet boşanma sebebi midir?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Sadakatsizlik boşanma davasında nasıl değerlendirilir?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma davasında kusur nedir?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Eşit kusur boşanma kararını nasıl etkiler?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Ağır kusurlu eşin itiraz hakkı', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },

  // Deliller
  { topic: 'Boşanma davasında hangi deliller kullanılır?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma davasında tanık beyanı', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma davasında WhatsApp kayıtları', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma davasında telefon kayıtları', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Sosyal medya paylaşımları boşanmada delil olur mu?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanmada ses kaydı delil olarak kullanılabilir mi?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Hukuka aykırı deliller boşanma davasında', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanmada banka kayıtları ve harcama delilleri', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanmada fotoğraf ve video delilleri', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Özel hayatın gizliliği ve boşanma delilleri', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },

  // Tazminat
  { topic: 'Boşanmada maddi tazminat şartları', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanmada manevi tazminat nasıl talep edilir?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanmada maddi ve manevi tazminat farkı', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma tazminatı miktarı nasıl belirlenir?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Kusursuz eş tazminat alabilir mi?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },

  // Velayet
  { topic: 'Velayet nedir ve kimlere verilir?', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Ortak velayet nedir?', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Türkiye’de ortak velayet mümkün mü?', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Çocuğun velayeti nasıl belirlenir?', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Velayet davasında hakim neye dikkat eder?', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Velayet değişikliği davası nasıl açılır?', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Velayet değişikliği için hangi şartlar gerekir?', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Geçici velayet nedir?', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Velayet davasında sosyal inceleme raporu', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Çocuğun görüşü velayet kararını etkiler mi?', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Bebek velayeti genellikle kime verilir?', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Baba velayet alabilir mi?', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Velayetin kaldırılması davası', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Kardeşlerin velayetinin ayrılması mümkün mü?', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Yurtdışına çıkışta velayet ve muvafakat', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },

  // Kişisel ilişki / çocuk teslimi
  { topic: 'Çocukla kişisel ilişki düzenlemesi nedir?', category: 'Çocukla Kişisel İlişki', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Çocuğu göstermeme halinde ne yapılır?', category: 'Çocukla Kişisel İlişki', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Çocuk teslimi nasıl yapılır?', category: 'Çocukla Kişisel İlişki', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Çocuk teslimine muhalefetin yaptırımı', category: 'Çocukla Kişisel İlişki', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Kişisel ilişki günlerinin ihlali', category: 'Çocukla Kişisel İlişki', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Kişisel ilişki kararının değiştirilmesi', category: 'Çocukla Kişisel İlişki', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Bayram ve tatilde çocukla kişisel ilişki', category: 'Çocukla Kişisel İlişki', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Uzaktan kişisel ilişki (görüntülü görüşme)', category: 'Çocukla Kişisel İlişki', practiceArea: 'Aile Hukuku, Velayet' },

  // Soybağı / babalık
  { topic: 'Soybağı davası nedir?', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Babalık davası nasıl açılır?', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Babalık davasında DNA testi', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Soybağının reddi davası', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Nüfus kaydında baba düzeltmesi', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },

  // Nafaka
  { topic: 'Nafaka türleri nelerdir?', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Tedbir nafakası nedir?', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Tedbir nafakası ne zaman sona erer?', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'İştirak nafakası nasıl belirlenir?', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'İştirak nafakası ne zamana kadar ödenir?', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Yoksulluk nafakası şartları', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Yoksulluk nafakası süreli mi süresiz mi?', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Nafaka nasıl hesaplanır?', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Nafaka artırım davası nasıl açılır?', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Nafaka artırımında hangi deliller kullanılır?', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Nafaka azaltma davası şartları', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Nafakanın kaldırılması davası', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Nafaka ödenmezse ne olur?', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Nafaka icra takibi nasıl yapılır?', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Çalışan eş yoksulluk nafakası alabilir mi?', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Nafaka alacaklısının yeniden evlenmesi', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Eğitim nafakası nedir?', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Boşanmadan bağımsız nafaka davası', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },

  // Mal rejimi / paylaşım
  { topic: 'Mal paylaşımı davası nedir?', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Edinilmiş mallara katılma rejimi nedir?', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Kişisel mallar ile edinilmiş malların farkı', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Mal rejimi tasfiyesi nasıl yapılır?', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Boşanmada ev kime kalır?', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Boşanmada araba nasıl paylaşılır?', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Boşanmada banka hesapları nasıl paylaşılır?', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Boşanmada şirket hissesi paylaşımı', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Mal ayrılığı rejimi nedir?', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Katılma alacağı nedir?', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Değer artış payı alacağı nedir?', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Mal paylaşımı davası ne zaman açılır?', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Mal paylaşımında zamanaşımı süresi', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Evlilik öncesi alınan mallar paylaşılır mı?', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Miras yoluyla gelen mallar boşanmada', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Boşanmada borçlar nasıl paylaşılır?', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },

  // Ziynet / düğün
  { topic: 'Ziynet alacağı davası nedir?', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Düğün takıları kime aittir?', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Ziynet eşyalarının ispatı nasıl yapılır?', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Ziynet alacağında zamanaşımı', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Düğün harcamaları boşanmada talep edilebilir mi?', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },

  // Aile konutu
  { topic: 'Aile konutu nedir?', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Aile konutu şerhi nasıl konulur?', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Aile konutu şerhi kaldırma davası', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Aile konutunun rıza dışı satışı', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Boşanmada aile konutu kiralama hakkı', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Aile konutu tapuda kimin adına olursa olsun korunur mu?', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },

  // 6284 / koruma
  { topic: 'Uzaklaştırma kararı nasıl alınır?', category: 'Koruma Tedbirleri', practiceArea: 'Aile Hukuku, Koruma Tedbirleri' },
  { topic: '6284 sayılı Kanun nedir?', category: 'Koruma Tedbirleri', practiceArea: 'Aile Hukuku, Koruma Tedbirleri' },
  { topic: 'Aile içi şiddet ve koruma tedbirleri', category: 'Koruma Tedbirleri', practiceArea: 'Aile Hukuku, Koruma Tedbirleri' },
  { topic: 'Uzaklaştırma kararına itiraz', category: 'Koruma Tedbirleri', practiceArea: 'Aile Hukuku, Koruma Tedbirleri' },
  { topic: 'Koruma tedbirinin ihlali halinde yaptırımlar', category: 'Koruma Tedbirleri', practiceArea: 'Aile Hukuku, Koruma Tedbirleri' },
  { topic: '6284 kapsamında konuttan uzaklaştırma', category: 'Koruma Tedbirleri', practiceArea: 'Aile Hukuku, Koruma Tedbirleri' },
  { topic: 'Şiddet mağduru için acil koruma başvurusu', category: 'Koruma Tedbirleri', practiceArea: 'Aile Hukuku, Koruma Tedbirleri' },

  // Uluslararası / tanıma tenfiz
  { topic: 'Tanıma ve tenfiz davası nedir?', category: 'Tanıma ve Tenfiz', practiceArea: 'Aile Hukuku, Tanıma ve Tenfiz' },
  { topic: 'Yurt dışında boşanma kararının Türkiye’de tanınması', category: 'Tanıma ve Tenfiz', practiceArea: 'Aile Hukuku, Tanıma ve Tenfiz' },
  { topic: 'Yabancı boşanma kararının tenfizi', category: 'Tanıma ve Tenfiz', practiceArea: 'Aile Hukuku, Tanıma ve Tenfiz' },
  { topic: 'Yurtdışında yaşayan Türklerin boşanma süreci', category: 'Tanıma ve Tenfiz', practiceArea: 'Aile Hukuku, Tanıma ve Tenfiz' },
  { topic: 'Uluslararası boşanmada yetkili mahkeme', category: 'Tanıma ve Tenfiz', practiceArea: 'Aile Hukuku, Tanıma ve Tenfiz' },
  { topic: 'Konsoloslukta boşanma mümkün mü?', category: 'Tanıma ve Tenfiz', practiceArea: 'Aile Hukuku, Tanıma ve Tenfiz' },
  { topic: 'Yabancı mahkeme velayet kararının Türkiye’de etkisi', category: 'Tanıma ve Tenfiz', practiceArea: 'Aile Hukuku, Tanıma ve Tenfiz' },

  // Uygulama / süreç detayları
  { topic: 'Boşanma davasında duruşmaya gitmezsem ne olur?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma davasında avukat zorunlu mu?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanmada e-Devlet ve UYAP süreçleri', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma davasında tebligat sorunları', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Gaiplik ve boşanma ilişkisi', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanmada ortak konuttan ayrılma', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma davasında ihtiyati tedbirler', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanmada ortak çocuk için geçici düzenlemeler', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Anlaşmalı boşanmada çocuk velayeti düzenlemesi', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Anlaşmalı boşanmada nafaka protokole nasıl yazılır?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Çekişmeli boşanmada kusur ispatı', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanmada ev eşyalarının paylaşımı', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Boşanmada kredi ödemeleri nasıl değerlendirilir?', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Boşanmada emeklilik ikramiyesi paylaşımı', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Boşanmada kıdem tazminatı mal rejiminde', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Nafaka artırımında enflasyon ve ÜFE etkisi', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'İştirak nafakasında çocuğun özel okul giderleri', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Velayet sahibi olmayan ebeveynin eğitim kararına katılımı', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Çocuğun okul seçiminde velayet ve kişisel ilişki', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Boşanmada aile konutu şerhinin önemi', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Şiddetli geçimsizlik boşanma sebebi midir?', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma davasında gizli delil toplama riskleri', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanmada e-posta ve bulut depolama delilleri', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Aile mahkemesinde ön inceleme duruşması', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Boşanma davasında bilirkişi incelemesi', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Nafaka davasında gelir araştırması nasıl yapılır?', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Yoksulluk nafakasında kusur şartı', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Tedbir nafakası ile yoksulluk nafakası farkı', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'İştirak nafakası ile yoksulluk nafakası birlikte talep', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Boşanma sonrası ortak velayet protokolü', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Velayet davasında ekonomik durumun rolü', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Çocukla kişisel ilişkide üçüncü kişi (büyükanne/dede)', category: 'Çocukla Kişisel İlişki', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Boşanmada ziynet listesi nasıl hazırlanır?', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Düğün takılarının iadesi davası', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Aile konutunda oturma hakkı boşanma sonrası', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: '6284 tedbir nafakası ile aile mahkemesi nafakası', category: 'Koruma Tedbirleri', practiceArea: 'Aile Hukuku, Koruma Tedbirleri' },
  { topic: 'Uzaklaştırma kararı süresi ve uzatılması', category: 'Koruma Tedbirleri', practiceArea: 'Aile Hukuku, Koruma Tedbirleri' },
  { topic: 'Yabancı ülkede alınan nafaka kararının Türkiye’de icrası', category: 'Tanıma ve Tenfiz', practiceArea: 'Aile Hukuku, Tanıma ve Tenfiz' },
  { topic: 'Lahey Sözleşmesi ve çocuk kaçırma', category: 'Tanıma ve Tenfiz', practiceArea: 'Aile Hukuku, Tanıma ve Tenfiz' },
  { topic: 'Uluslararası çocuk kaçırma davalarında süreç', category: 'Tanıma ve Tenfiz', practiceArea: 'Aile Hukuku, Tanıma ve Tenfiz' },
  { topic: 'Boşanmada mal rejimi başlangıç tarihi', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: '2002 öncesi evliliklerde mal rejimi', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Boşanmada katkı payı alacağı', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Eşin maaşının mal rejimindeki yeri', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Boşanmada bağışlanan malların durumu', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Anlaşmalı boşanmada mal paylaşımı protokole yazılmazsa', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Çekişmeli boşanmada mal paylaşımı ayrı dava mı?', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Boşanma davasında gizli mal kaçırma iddiası', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Nafaka borçlusunun işsiz kalması', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'İştirak nafakasında üniversite öğrencisi çocuk', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Velayet değişikliğinde çocuğun alışkanlıkları', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Boşanmada psikolojik şiddetin ispatı', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanmada aile içi iletişim kayıtları', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Aile mahkemesinde sulh teşviki', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Boşanma kararında nafaka artırım hükmü', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Boşanmada geçici hukuki koruma tedbirleri', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Çocukla kişisel ilişkide denetimli görüşme', category: 'Çocukla Kişisel İlişki', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Boşanmada evlilik birliği içinde yapılan yatırımlar', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Aile konutu şerhi olmadan satışın iptali', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: '6284 kapsamında silah teslimi ve iletişim yasağı', category: 'Koruma Tedbirleri', practiceArea: 'Aile Hukuku, Koruma Tedbirleri' },
  { topic: 'Yurt dışı boşanmanın Türkiye’de nüfusa işlenmesi', category: 'Tanıma ve Tenfiz', practiceArea: 'Aile Hukuku, Tanıma ve Tenfiz' },
  { topic: 'Boşanmada ortak hayvan (pet) uyuşmazlıkları', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanmada evlilik hediyelerinin iadesi', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Nişanlılıkta verilen ziynetlerin iadesi', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Evlat edinmede çocuğun rızası', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Boşanmada aile konutunun tahliyesi', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Boşanma davasında karşı dava açılması', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanmada birleşen davalar ve feriler', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Nafaka alacağında haciz ve maaş kesintisi', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Velayet sahibinin şehir değiştirmesi', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Boşanmada ortak konut anahtarının teslimi', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
];

/** Extra niche intents used only when primary pool is exhausted. */
export const FALLBACK_TOPIC_POOL = [
  { topic: 'Boşanma davasında gizlilik kararı', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanmada eşin yurt dışına kaçması', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma sonrası ortak borçlara kefalet', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Nafaka artırımında çocuğun sağlık giderleri', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'İştirak nafakasında özel ders ve kurs ücretleri', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Yoksulluk nafakasında fiilen yeniden evlenme benzeri yaşam', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Velayet davasında kardeş bağının korunması', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Kişisel ilişki kararında yol masrafı', category: 'Çocukla Kişisel İlişki', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Çocuk teslim merkezinde görüşme süreci', category: 'Çocukla Kişisel İlişki', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Boşanmada aile konutu kira sözleşmesinin feshi', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Aile konutu şerhinin alacaklılara etkisi', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Ziynet alacağında tanık delili', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Düğün takılarının satılması halinde tazminat', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Mal paylaşımında ekspertiz ve değer tespiti', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Boşanmada kripto varlıkların tasfiyesi', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: '6284 tedbirlerinin boşanma davasına etkisi', category: 'Koruma Tedbirleri', practiceArea: 'Aile Hukuku, Koruma Tedbirleri' },
  { topic: 'Uzaklaştırma kararında elektronik kelepçe', category: 'Koruma Tedbirleri', practiceArea: 'Aile Hukuku, Koruma Tedbirleri' },
  { topic: 'Babalık davasında zamanaşımı', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Soybağının reddinde genetik inceleme', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Tanıma tenfizde kamu düzeni engeli', category: 'Tanıma ve Tenfiz', practiceArea: 'Aile Hukuku, Tanıma ve Tenfiz' },
  { topic: 'Yabancı boşanmada velayet hükmünün tenfizi', category: 'Tanıma ve Tenfiz', practiceArea: 'Aile Hukuku, Tanıma ve Tenfiz' },
  { topic: 'Boşanmada müşterek çocuk için pasaport işlemi', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Anlaşmalı boşanmada feragat edilen haklar', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Çekişmeli boşanmada ıslah ve ek talep', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanma davasında kesin süreler', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Nafaka davasında ihtiyati haciz', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'İştirak nafakasında ergin çocuğun talebi', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Boşanmada manevi tazminatın ispat ölçütü', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Aile mahkemesinde duruşma erteleme sebepleri', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
  { topic: 'Boşanmada ortak evin satışı yasağı', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: 'Velayet sahibinin çocuğu yurt dışına götürmesi', category: 'Velayet', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Kişisel ilişki ihlalinde disiplin hapsi', category: 'Çocukla Kişisel İlişki', practiceArea: 'Aile Hukuku, Velayet' },
  { topic: 'Boşanmada evlilik birliği giderlerine katkı', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Mal rejiminde eşin kişisel kullanım eşyaları', category: 'Mal Paylaşımı', practiceArea: 'Aile Hukuku, Mal Rejimi' },
  { topic: '6284 kapsamında çocuklar için koruma tedbirleri', category: 'Koruma Tedbirleri', practiceArea: 'Aile Hukuku, Koruma Tedbirleri' },
  { topic: 'Yurt dışı tebligatlı boşanma davası', category: 'Tanıma ve Tenfiz', practiceArea: 'Aile Hukuku, Tanıma ve Tenfiz' },
  { topic: 'Boşanmada sosyal medya takibi ve delil değeri', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Nafaka artırımında tarafların yeni gelirleri', category: 'Nafaka', practiceArea: 'Aile Hukuku, Nafaka' },
  { topic: 'Anlaşmalı boşanma protokolünde cezai şart', category: 'Boşanma Hukuku', practiceArea: 'Aile Hukuku, Boşanma Hukuku' },
  { topic: 'Boşanmada aile konutu şerhi ile ipotek ilişkisi', category: 'Aile Hukuku', practiceArea: 'Aile Hukuku' },
];
